version: '3.8'

services:
  waitlist:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/waitlist.db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-change-this}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@skygen.ai}
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT:-587}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
    volumes:
      - waitlist_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  waitlist_data:
    driver: local
